apiVersion: v1
kind: Service
metadata:
  name: predictor-service
  namespace: kubeflow-user-example-com
spec:
  type: NodePort
  selector:
    app: digits-recognizer-predictor-default-00001
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP